services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: express_app
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-secret}@db:5432/${POSTGRES_DB:-appdb}
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app        # hot-reload in development
      - /app/node_modules # prevent host from overwriting container modules
    depends_on:
      db:
        condition: service_healthy

  alert:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: alert_service
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-secret}@db:5432/${POSTGRES_DB:-appdb}
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 8080
    command: ["node", "jobs/alertService.js"]
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app        # hot-reload in development
      - /app/node_modules # prevent host from overwriting container modules


volumes:
  postgres_data:
